server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zzaki111/SpringCloudConfigDemo
          search-paths: test-config-dir
  application:
    name: config-server
security:
  user:
    name: zzaki
    password: 123456
eureka:
  client:
    service-url.defaultZone: http://localhost:1111/eureka/
